"""Copy the TRIOS reader in from ACH-DSC-Plotter.

    python tools/vendor.py                  # from the sibling repo
    python tools/vendor.py --from <path>    # from somewhere else
    python tools/vendor.py --check          # exit 1 if the copy is stale

WHY A COPY AND NOT A DEPENDENCY: ACH-DSC-Plotter is a private repo, so a
`pip install ach-dsc-panel` that depended on it would need credentials and a
git URL. The reader is also the one part of this program that must keep
working untouched for years - it is a reverse-engineered binary format - so a
copy that is updated deliberately is safer than one that moves under the
program's feet. This is the same arrangement the DSC_Plotter.py template
already uses, and `dsc -u` there is the same idea as `--check` here.

The copies carry a header saying where they came from and when, so a bug can
always be traced back to the version of the reader that had it. `--check` is
what a test calls: it says whether the copy still matches the source, so
drift is noticed rather than discovered.
"""

import argparse
import datetime as _dt
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
TARGET_DIR = os.path.join(REPO, "src", "dscpanel", "core")

#: Default source: the sibling checkout of the plotter repo.
DEFAULT_SOURCE = os.path.join(os.path.dirname(REPO), "ACH-DSC-Plotter",
                              "src", "achdsc")

#: The modules taken over, and nothing else. `trios_artists.py` is
#: deliberately NOT vendored: it draws with matplotlib, and this program
#: paints with QPainter, so its drawing has a new implementation here rather
#: than a copy that would never be called.
MODULES = ("trios_io.py", "trios_analysis.py")

HEADER = """# VENDORED from ACH-DSC-Plotter {version} on {date}.
# Source: src/achdsc/{name}   sha256 {digest}
#
# Do not edit this file here. Fix it in ACH-DSC-Plotter (where TRI-FORMAT.md
# and the reader tests live), then run `python tools/vendor.py` again.
# `python tools/vendor.py --check` reports when this copy has gone stale.
"""

MARK = "# VENDORED from ACH-DSC-Plotter"


def source_version(source_dir):
    """The version of the package being copied from, or 'unknown'."""
    init = os.path.join(source_dir, "__init__.py")
    try:
        with open(init, "r", encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("__version__"):
                    return line.split("=", 1)[1].strip().strip("\"'")
    except OSError:
        pass
    return "unknown"


def _read(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def _strip_header(text):
    """The file without a vendoring header, for comparing copies."""
    lines = text.splitlines(True)
    while lines and (lines[0].startswith(MARK) or lines[0].startswith("# ")
                     or lines[0].strip() == "#"):
        if lines[0].startswith(MARK):
            while lines and lines[0].startswith("#"):
                lines.pop(0)
            while lines and not lines[0].strip():
                lines.pop(0)
            break
        break
    return "".join(lines)


def vendor(source_dir, check=False):
    """Copy (or check) every module. Returns the number that are stale."""
    version = source_version(source_dir)
    stale = 0
    for name in MODULES:
        src = os.path.join(source_dir, name)
        if not os.path.isfile(src):
            print("missing source: {}".format(src))
            return -1
        text = _read(src)
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
        dst = os.path.join(TARGET_DIR, name)
        current = _read(dst) if os.path.isfile(dst) else ""
        if _strip_header(current) == text:
            print("{}: up to date ({})".format(name, version))
            continue
        stale += 1
        if check:
            print("{}: STALE - run python tools/vendor.py".format(name))
            continue
        header = HEADER.format(version=version, name=name, digest=digest,
                               date=_dt.date.today().isoformat())
        with open(dst, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(header + "\n" + text)
        print("{}: copied from {} ({})".format(name, source_dir, version))
    return stale


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--from", dest="source", default=DEFAULT_SOURCE,
                    help="the achdsc package directory to copy from")
    ap.add_argument("--check", action="store_true",
                    help="report stale copies instead of writing them")
    args = ap.parse_args(argv)
    stale = vendor(os.path.abspath(args.source), check=args.check)
    if stale < 0:
        return 2
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
